<a href="https://colab.research.google.com/github/githubsiddharth07/next-Word-Predictor/blob/main/nextWord.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
dataset="""The morning of June 27th was clear and sunny, with the fresh warmth of a full-summer day; the flowers were blossoming profusely and the grass was richly green. The people of the village began to gather in the square, between the post office and the bank, around ten o’clock; in some towns there were so many people that the lottery took two days and had to be started on June 26th, but in this village, where there were only about three hundred people, the whole lottery took only about two hours, so it could begin at ten o’clock in the morning and still be through in time to allow the villagers to get home for noon dinner.

The children assembled first, of course. School was recently over for the summer, and the feeling of liberty sat uneasily on most of them; they tended to gather together quietly for a while before they broke into boisterous play, and their talk was still of the classroom and the teacher, of books and reprimands. Bobby Martin had already stuffed his pockets full of stones, and the other boys soon followed his example, selecting the smoothest and roundest stones; Bobby and Harry Jones and Dickie Delacroix—the villagers pronounced this name “Dellacroy”—eventually made a great pile of stones in one corner of the square and guarded it against the raids of the other boys. The girls stood aside, talking among themselves, looking over their shoulders at the boys, and the very small children rolled in the dust or clung to the hands of their older brothers or sisters.

Soon the men began to gather, surveying their own children, speaking of planting and rain, tractors and taxes. They stood together, away from the pile of stones in the corner, and their jokes were quiet and they smiled rather than laughed. The women, wearing faded house dresses and sweaters, came shortly after their menfolk. They greeted one another and exchanged bits of gossip as they went to join their husbands. Soon the women, standing by their husbands, began to call to their children, and the children came reluctantly, having to be called four or five times. Bobby Martin ducked under his mother’s grasping hand and ran, laughing, back to the pile of stones. His father spoke up sharply, and Bobby came quickly and took his place between his father and his oldest brother.

The lottery was conducted—as were the square dances, the teen-age club, the Halloween program—by Mr. Summers, who had time and energy to devote to civic activities. He was a round-faced, jovial man and he ran the coal business, and people were sorry for him, because he had no children and his wife was a scold. When he arrived in the square, carrying the black wooden box, there was a murmur of conversation among the villagers, and he waved and called, “Little late today, folks.” The postmaster, Mr. Graves, followed him, carrying a three-legged stool, and the stool was put in the center of the square and Mr. Summers set the black box down on it. The villagers kept their distance, leaving a space between themselves and the stool, and when Mr. Summers said, “Some of you fellows want to give me a hand?,” there was a hesitation before two men, Mr. Martin and his oldest son, Baxter, came forward to hold the box steady on the stool while Mr. Summers stirred up the papers inside it.

The original paraphernalia for the lottery had been lost long ago, and the black box now resting on the stool had been put into use even before Old Man Warner, the oldest man in town, was born. Mr. Summers spoke frequently to the villagers about making a new box, but no one liked to upset even as much tradition as was represented by the black box. There was a story that the present box had been made with some pieces of the box that had preceded it, the one that had been constructed when the first people settled down to make a village here. Every year, after the lottery, Mr. Summers began talking again about a new box, but every year the subject was allowed to fade off without anything’s being done. The black box grew shabbier each year; by now it was no longer completely black but splintered badly along one side to show the original wood color, and in some places faded or stained."""

In [2]:
import tensorflow as tf

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [4]:
tokenizer=Tokenizer()

In [5]:
tokenizer.fit_on_texts([dataset])

In [25]:
print(len(tokenizer.word_index))

336


In [11]:
input_sequences=[]
for sentence in dataset.split('\n'):
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [12]:
input_sequences

[[1, 57],
 [1, 57, 3],
 [1, 57, 3, 58],
 [1, 57, 3, 58, 105],
 [1, 57, 3, 58, 105, 5],
 [1, 57, 3, 58, 105, 5, 106],
 [1, 57, 3, 58, 105, 5, 106, 2],
 [1, 57, 3, 58, 105, 5, 106, 2, 107],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109, 3],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109, 3, 6],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109, 3, 6, 60],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109, 3, 6, 60, 61],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109, 3, 6, 60, 61, 110],
 [1, 57, 3, 58, 105, 5, 106, 2, 107, 59, 1, 108, 109, 3, 6, 60, 61, 110, 1],
 [1,
  57,
  3,
  58,
  105,
  5,
  106,
  2,
  107,
  59,
  1,
  108,
  109,
  3,
  6,
  60,
  61,
  110,
  1,
  111],
 [1,
  57,
  3,
  58,
  105,
  5,
  106,
  2,
  107,
  59,
  1,
  108,
  109,
  3,
  6,
  60,
  

In [13]:
max_len=max(len(x) for x in input_sequences)

In [17]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,max_len,padding='pre')

In [18]:
print(max_len)

181


In [19]:
X=padded_input_sequences[:,:-1]
print(X)

[[  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   1  57]
 [  0   0   0 ...   1  57   3]
 ...
 [  0   0   0 ...   7  41 335]
 [  0   0   0 ...  41 335  86]
 [  0   0   0 ... 335  86  35]]


In [20]:
print(padded_input_sequences)

[[  0   0   0 ...   0   1  57]
 [  0   0   0 ...   1  57   3]
 [  0   0   0 ...  57   3  58]
 ...
 [  0   0   0 ...  41 335  86]
 [  0   0   0 ... 335  86  35]
 [  0   0   0 ...  86  35 336]]


In [21]:
Y=padded_input_sequences[:,-1]

In [22]:
print(Y)

[ 57   3  58 105   5 106   2 107  59   1 108 109   3   6  60  61 110   1
 111  13 112 113   2   1 114   5 115 116   1  19   3   1  38  30   4  39
   7   1  20  40   1 117 118   2   1 119 120  62  63   7  41 121  21  13
  64 122  19  31   1  22  42  43 123   2  10   4  44 124  23  58 125  32
   7  65  38 126  21  13  66  33  67 127  19   1 128  22  42  66  33  43
 129  64  14 130 131  68  62  63   7   1  57   2  69  44 132   7  70   4
 133   1  24   4 134 135  25 136 137  15 138  71   3 139 140   5 141  72
  25   1  61   2   1 142   3 143 144 145  23 146   3 147  16 148   4  39
  73 149  25   6  74  45  16 150  75 151 152   2   8 153   5  69   3   1
 154   2   1 155   3 156   2 157  34  46  10 158 159  11 160  60   3  26
   2   1  76  47  48  77  11 161 162   1 163   2 164  26  34   2 165 166
   2 167 168  24 169  65 170 171  78   6 172  49   3  26   7  27  79   3
   1  20   2 173  14 174   1 175   3   1  76  47   1 176  80 177  81  82
  83 178  72   8 179  68   1  47   2   1 180 181  1

In [23]:
X.shape

(739, 180)

In [24]:
Y.shape

(739,)

In [26]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(Y,num_classes=337)
y.shape

(739, 337)

In [27]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [41]:
model=Sequential()
model.add(Embedding(337,100,input_length=180))
model.add(LSTM(150))
model.add(Dense(337,activation='softmax'))

In [42]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [43]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 180, 100)          33700     
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 337)               50887     
                                                                 
Total params: 235187 (918.70 KB)
Trainable params: 235187 (918.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:
model.fit(X,y,epochs=100)

Epoch 1/100
24/24 [==============================] - 13s 445ms/step - loss: 5.6946 - accuracy: 0.0758
Epoch 2/100
24/24 [==============================] - 8s 314ms/step - loss: 5.3513 - accuracy: 0.0866
Epoch 3/100
24/24 [==============================] - 9s 387ms/step - loss: 5.2331 - accuracy: 0.0866
Epoch 4/100
24/24 [==============================] - 7s 292ms/step - loss: 5.2072 - accuracy: 0.0866
Epoch 5/100
24/24 [==============================] - 9s 387ms/step - loss: 5.1829 - accuracy: 0.0866
Epoch 6/100
24/24 [==============================] - 7s 287ms/step - loss: 5.1625 - accuracy: 0.0866
Epoch 7/100
24/24 [==============================] - 9s 383ms/step - loss: 5.1282 - accuracy: 0.0866
Epoch 8/100
24/24 [==============================] - 7s 287ms/step - loss: 5.0737 - accuracy: 0.0907
Epoch 9/100
24/24 [==============================] - 9s 376ms/step - loss: 4.9944 - accuracy: 0.1069
Epoch 10/100
24/24 [==============================] - 8s 335ms/step - loss: 4.8917 - accur

In [45]:
import time

In [48]:
import numpy as np
text="School"
for i in range(10):
  # tokenizing
  token_text=tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text=pad_sequences([token_text],maxlen=180,padding='pre')
  # predict
  pos=np.argmax(model.predict(padded_token_text))
  for word,index in tokenizer.word_index.items():
    if index == pos:
      text=text+" "+word
      print(text)
      time.sleep(1)

1/1 [==============================] - 0s 52ms/step
School was
1/1 [==============================] - 0s 77ms/step
School was recently
1/1 [==============================] - 0s 91ms/step
School was recently over
1/1 [==============================] - 0s 53ms/step
School was recently over for
1/1 [==============================] - 0s 61ms/step
School was recently over for the
1/1 [==============================] - 0s 51ms/step
School was recently over for the men
1/1 [==============================] - 0s 57ms/step
School was recently over for the men began
1/1 [==============================] - 0s 53ms/step
School was recently over for the men began to
1/1 [==============================] - 0s 53ms/step
School was recently over for the men began to gather
1/1 [==============================] - 0s 51ms/step
School was recently over for the men began to gather surveying
